(def equal-wrt-testing (a b)
  (if (and (isa a 'exception) (isa b 'exception))
       (is (details a) (details b))
      (and (isa a 'table) (isa b 'table))
       (with (ka (keys a) kb (keys b))
         (and (is (len ka) (len kb))
              (equal-wrt-testing (sort < ka) (sort < kb))
              (all [equal-wrt-testing a._ b._] ka)))
      (and (acons a) (acons b))
       (and (equal-wrt-testing (car a) (car b))
            (equal-wrt-testing (cdr a) (cdr b)))
       (iso a b)))
